CREATE DATABASE nhom3
GO
USE nhom3
GO
CREATE TABLE DEAN(
	TENDA	NVARCHAR(15),
	MADA INT,
	DDIEM_DA NVARCHAR(15),
	PHONG INT
	CONSTRAINT DEAN_pk PRIMARY KEY (MADA)
)

CREATE TABLE PHONGBAN(
	TENPHG	NVARCHAR(15),
	MAPHG INT,
	TRPHG NVARCHAR(9),
	NG_NHANCHUC DATE
	CONSTRAINT PHONGBAN_pk PRIMARY KEY (MAPHG)
)

CREATE TABLE DIADIEM_PHG(
	MAPHG INT,
	DIADIEM NVARCHAR(15)
	CONSTRAINT DIADIEM_PHG_pk PRIMARY KEY (MAPHG,DIADIEM)
)


CREATE TABLE NHANVIEN(
	HONV NVARCHAR(15),
	TENLOT NVARCHAR(15),
	TENNV NVARCHAR(15),
	MANV NVARCHAR(9),
	NGSINH date,
	DCHI NVARCHAR(30),
	PHAI NVARCHAR(5),
	LUONG float,
	MA_NQL NVARCHAR(9),
	PHG int
	CONSTRAINT NHANVIEN_pk PRIMARY KEY (MANV)

)



CREATE TABLE THANNHAN(
	MANV NVARCHAR(9),
	TENTN NVARCHAR(15),
	PHAI NVARCHAR(5),
	NGSINH date,
	QUANHE NVARCHAR(15)
	CONSTRAINT THANNHAN_pk PRIMARY KEY (MANV,TENTN)
)


CREATE TABLE CONGVIEC(
	MADA INT,
	STT INT,
	TEN_CONG_VIEC NVARCHAR(50)
	CONSTRAINT CONGVIEC_pk PRIMARY KEY (STT,MADA)
)

CREATE TABLE PHANCONG(
	MANV NVARCHAR(9),
	MADA INT,
	STT INT,
	THOIGIAN DATE
	CONSTRAINT PHANCONG_pk PRIMARY KEY (MANV,MADA,STT)
)


ALTER TABLE DEAN
ADD CONSTRAINT  fk_DEAN FOREIGN KEY (PHONG) REFERENCES PHONGBAN (MAPHG)

ALTER TABLE PHONGBAN
ADD CONSTRAINT fk_PHONGBAN FOREIGN KEY (MAPHG) REFERENCES NHANVIEN (PHG)


ALTER TABLE DIADIEM_PHG
ADD CONSTRAINT fk_DIADIEM_PHG FOREIGN KEY (MAPHG) REFERENCES PHONGBAN (MAPHG)

ALTER TABLE CONGVIEC
ADD CONSTRAINT fk_CONGVIEC FOREIGN KEY (MADA) REFERENCES DEAN (MADA)

ALTER TABLE NHANVIEN
ADD CONSTRAINT fk_NHANVIEN FOREIGN KEY (MANV) REFERENCES PHONGBAN (TRPHG)

ALTER TABLE NHANVIEN
ADD CONSTRAINT fk_NHANVIEN1 FOREIGN KEY (PHG) REFERENCES PHONGBAN (MAPHG)

ALTER TABLE PHANCONG
ADD CONSTRAINT fk_PHANCONG FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV)

ALTER TABLE PHANCONG
ADD CONSTRAINT fk_PHANCONG1 FOREIGN KEY (STT) REFERENCES CONGVIEC (STT)

ALTER TABLE THANNHAN
ADD CONSTRAINT fk_THANNHAN FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV)

BEGIN
ALTER TABLE DEAN
INSERT INTO DEAN(TENDA,MADA,DDIEM_DA,PHONG) VALUES
(N'Sản phẩm X', 1, N'Vũng Tàu', 5),
(N'Sản phẩm Y', 2, N'Nha Trang', 5),
(N'Sản phẩm Z', 3, N'TP HCM', 5),
(N'Tin Học Hoá', 10, N'Hà Nội',4),
(N'Cáp Quang',20,N'TP HCM',1),
(N'Đào Tạo',30,N'Hà Nội',4)
END

BEGIN
ALTER TABLE PHONGBAN
INSERT INTO PHONGBAN(TENPHG,MAPHG,TRPHG ,NG_NHANCHUC) VALUES
(N'Nghiên cứu' , 5, '005', '1978/05/22'),
(N'Điều Hành', 4, '008', '1985/01/01'),
(N'Quản Lý', 1, '006', '1971/06/19')
END

BEGIN
ALTER TABLE DIADIEM_PHG
INSERT INTO DIADIEM_PHG(MAPHG,DIADIEM) VALUES
(1 ,N'TP HCM'),
(4, N'Hà Nội'),
(5, N'TAU'),
(5, N'NHA TRANG'),
(5, N'TP HCM')
END

BEGIN
ALTER TABLE NHANVIEN
INSERT INTO NHANVIEN(HONV,TENLOT,TENNV,MANV,NGSINH,DCHI,PHAI,LUONG,MA_NQL,PHG) VALUES
(N'Đinh',N'Bá',N'Tiên', '009', '1960/02/11',N'119 Cống Quỳnh,TPHCM',N'nam',30000,005,5),
(N'Nguyễn',N'Thanh',N'Tùng', '005', '1962/08/20',N'222 Nguyễn Văn Cừ,TPHCM',N'nam',40000,006,5),
(N'Bùi',N'Ngọc',N'Hằng', '007', '1954/03/11',N'332 Nguyễn Thái Học,TPHCM',N'nam',25000,001,4),
(N'Lê',N'Quỳnh',N'Như', '001', '1967/02/01',N'291 Hồ Văn Huê,TPHCM',N'nữ',43000,006,4),
(N'Nguyễn',N'Mạnh',N'Hùng', '004', '1967/03/04',N'95 Bà Rịa, Vũng Tàu',N'nam',38000,005,5),
(N'Trần',N'Thanh',N'Tâm','003','1957/05/04',N'34 Mai Thị Lự,TPHCM',N'nam',25000,005,5),
(N'Trần',N'Hồng',N'Quang','008','1967/09/01',N'80 Lê Hồng Phong,TPHCM',N'nam',25000,001,4),
(N'Phạm',N'Văn',N'Vinh', '006','1965/01/01',N'45 Trưng Vương, Hà Nội',N'nữ',55000,null,1)
END
BEGIN
ALTER TABLE THANNHAN
INSERT INTO THANNHAN(MANV,TENTN,PHAI,NGSINH,QUANHE) VALUES
('005',N'Trinh', N'nữ', '1976/04/05'),
('005',N'Khang',N'nam','1973/10/25'),
('005',N'Phương',N'nữ','1948/05/03'),
('001',N'Minh',N'nam','1932/02/29'),
('009',N'Tiến',N'nam','1978/01/01'),
('009',N'Châu',N'nữ','1978/12/30'),
('009',N'Phương',N'nữ','1957/05/05')
END

BEGIN
ALTER TABLE CONGVIEC
INSERT INTO CONGVIEC(MADA,STT,TEN_CONG_VIEC) VALUES
(1,1,N'Thiết kế sản phẩm X'),
(1,2,N'Thử nghiệm sản phẩm X'),
(2,1,N'Sản xuất sản phẩm Y'),
(2,2,N'Quảng cáo sản phẩm Z'),
(3,1,N'Khuyến mãi sản phẩm Z'),
(10,1,N'Tin học hoá phòng nhân sự'),
(10,2,N'Tin học hoá phòng kinh doanh'),
(20,1,N'Lắp đặt cáp quang'),
(30,1,N'Đào tạo nhân viên Marketing'),
(30,2,N'Đào tạo chuyên viên thiết kế')
END

BEGIN
ALTER TABLE PHANCONG
INSERT INTO PHANCONG(MANV,MADA,STT,THOIGIAN) VALUES
('009',1,1,'32'),
('009',2,2,'8'),
('004',3,1,'40'),
('003',1,2,'20.0'),
('003',2,1,'20.0'),
('008',10,1,'35'),
('008',30,2,'5'),
('001',30,1,'20'),
('001',20,1,'15'),
('006',20,1,'30'),
('005',3,1,'10'),
('005',10,2,'10'),
('005',20,1,'10'),
('007',30,2,'30'),
('007',10,2,'10')
END

BEGIN
/*B1*/

SELECT  *
FROM NHANVIEN
WHERE LUONG=(SELECT MAX (LUONG) FROM NHANVIEN)

/*B2*/
SELECT (NHANVIEN.HONV + ' ' + NHANVIEN.TENLOT + ' ' + NHANVIEN.TENNV) AS 'Họ tên nhân viên có lương trung bình trên mức lương trung bình của phòng "Nghiên cứu"'
	FROM NHANVIEN
	WHERE NHANVIEN.LUONG > (SELECT AVG(NHANVIEN.LUONG)
							FROM NHANVIEN, PHONGBAN
							WHERE NHANVIEN.PHG = PHONGBAN.MAPHG AND
								  PHONGBAN.TENPHG = N'Nghiên cứu')

/*B3*/
SELECT PHONGBAN.TENPHG, COUNT(NHANVIEN.MANV) AS N'Số lượng nhân viên'
	FROM NHANVIEN, PHONGBAN
	WHERE NHANVIEN.PHG = PHONGBAN.MAPHG
	GROUP BY PHONGBAN.TENPHG
	HAVING AVG(NHANVIEN.LUONG)>30000

/*B4*/
SELECT PHONGBAN.TENPHG, COUNT(DEAN.PHONG) AS 'Số lượng đề án'
	FROM PHONGBAN, DEAN
	WHERE PHONGBAN.MAPHG = DEAN.PHONG
	GROUP BY PHONGBAN.TENPHG

END